### ISSUE TITLE
VonNeumannTests failed on Windows 10 Home

### ISSUE THREAD

**Issue by roy77** [hneemann/Assembler#1]
VonNeumannTest.testHarvard:20 null expected:<v2.0 raw[
1400
5220
8041
1200
5200
5210
1400
1403]
> but was:<v2.0 raw[
1400
5220
8041
1200
5200
5210
1400
1403
]
>
  VonNeumannTest.testVonNeumann:33 null expected:<v2.0 raw[
41
41
0
1400
8000
1300]
> but was:<v2.0 raw[
41
41
0
1400
8000
1300
]
>

**Comment by hneemann** [comment]
fixed!
